app_forum/urls.py
from django.conf.urls import url
from .views import index, add_post, post, add_comment

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_post', add_post, name='add_post'),
    url(r'^post/(?P<pk>\d+)/add_comment/$', add_comment, name='add_comment'),
    url(r'^post/(?P<pk>\d+)/$', post, name='post'),
]

app_login/urls.py
from django.conf.urls import url
from .views import index, add_commentlog

urlpatterns = [
    url(r'^$', index, name='index'),
    
]

app_profile/urls.py
from .views import index
from django.conf.urls import url, include

urlpatterns = [
    url(r'^$', index, name='index')
]

t2ka/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_login.urls as app_login
import app_profile.urls as app_profile
from app_login.views import index as index_login
import app_forum.urls as app_forum
from app_login.views import post, add_commentlog
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index_login, name='index'),
    url(r'^(?P<pk>\d+)/add_comment/$', add_commentlog, name='add_commentlog'),
    url(r'^profile/', include(app_profile,namespace='profile')),
    url(r'^forum/', include(app_forum,namespace='forum')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^(?P<pk>\d+)/$', post, name='post'),
]

app_forum/models.py
from django.db import models
from tinymce.models import HTMLField
class Post(models.Model):
    name = models.CharField(max_length=27)
    judul = models.CharField(max_length=180)
    content = HTMLField()#models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    name = models.CharField(max_length=27)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, related_name='posts')

app_login/models.py
from django.db import models

# Create your models here.

app_profile/models.py
from django.db import models

# Create your models here.

app_forum/forms.py
from django import forms

class Post_Form(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    judul = forms.CharField(widget=forms.TextInput(attrs=attrs), required=True)
    content = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

class Comment_Form(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    content = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

app_forum/views.py
from django.shortcuts import render, get_object_or_404
from .forms import Post_Form, Comment_Form
from .models import Post, Comment
from django.http import HttpResponseRedirect
# Create your views here.
response = {}

def index(request):
    html = 'forum.html'
    response['post_form'] = Post_Form
    posting = Post.objects.all()
    response['posts'] = posting
    return render(request, html, response)

def add_post(request):
    form = Post_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        name = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        judul = request.POST['judul']
        content = request.POST['content']
        posts = Post(name=name, judul=judul,
                          content=content)
        posts.save()
        return HttpResponseRedirect('/forum/')

def post(request, pk):
    post = Post.objects.get(pk=pk)
    comment = Comment.objects.filter(post=post)
    response['comment_form'] = Comment_Form
    response['post']=post
    response['comments']=comment
    return render(request, 'post.html', response)

def add_comment(request, pk):
    form = Comment_Form(request.POST or None)
    post = get_object_or_404(Post,pk=pk)
    if(request.method == 'POST' and form.is_valid()):
        name = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        content = request.POST['content']
        comments = Comment(name=name,
                          content=content, post=post)
        comments.save()
        return HttpResponseRedirect('/forum/post/'+pk+'/')

app_login/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from app_forum.models import Post, Comment
from app_forum.forms import Comment_Form
from django.contrib import messages
# Create your views here.
response = {}

def index(request):
    html = 'login.html'
    posting = Post.objects.all()
    response['posts'] = posting
    return render(request, html, response)

def login(request):
    html = 'loggedin.html'
    posting = Post.objects.all()
    response['posts'] = posting
    return render(request, html, response)

def post(request, pk):
    post = Post.objects.get(pk=pk)
    comment = Comment.objects.filter(post=post)
    response['comment_form'] = Comment_Form
    response['post']=post
    response['comments']=comment
    return render(request, 'postlog.html', response)

def add_commentlog(request, pk):
    form = Comment_Form(request.POST or None)
    post = get_object_or_404(Post,pk=pk)
    if(request.method == 'POST' and form.is_valid()):
        if request.POST['name'] == post.name:
            messages.info(request, 'Silakan pilih nama lain')
            return HttpResponseRedirect('/'+pk+'/')
        else:
            name = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
            content = request.POST['content']
            comments = Comment(name=name,content=content, post=post)
            comments.save()
            return HttpResponseRedirect('/'+pk+'/')
    else:
        messages.info(request, 'Komentar tidak boleh kosong')
        return HttpResponseRedirect('/'+pk+'/')

app_profile/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
response = {}

def index(request):
    html = 'profile.html'
    return render(request, html, response)

app_forum/templates/forum.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Page Contents -->
    <script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tinymce/custom.js' %}" ></script>


    <script>
    var data= JSON.parse(sessionStorage.getItem("data"));
    if (data==null) {
      alert('login dolo');
      $(location).attr('href', "{% url 'index' %}");
    }
	   $(document).ready(function(){
      $('#id_name').val(data["name"]);
    });
    </script>
    <div class="ui grid container" style="margin-bottom:5rem;margin-top:10rem">
      <div class="ui breadcrumb">
  <a href="{% url 'index' %}" class="section">Home</a>
  <div class="divider"> / </div>
  <div class="active section">Forum</div>
</div>
    <table class="ui celled striped table">
      <thead>
        <tr><th colspan="3">
          <h3>Forum BukaHati</h3>
        </th>
      </tr></thead>
      <tbody>
        {% for i in posts %}
        <tr>
          <td><a href="{% url 'forum:post' i.pk %}">{{ i.judul }}</a></td>
          <td class="right aligned collapsing">{{ i.created_date }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <table class="ui celled striped table">
<form id="form" method="POST" action="{% url 'forum:add_post' %}" class="ui form">
      <thead>
        <tr><th colspan="3">
          <h3>Buat Forum</h3>
        </th>
      </tr></thead>
<tbody>
        {% csrf_token %}
        {{ post_form }}
        <tr>
                <td colspan="2">
                <button type="submit" class="ui button">Submit</button></td>

        </tr>
    </tbody>
</form>
    </table>

  </div>
{% endblock %}

app_forum/templates/post.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Page Contents -->
    <script>
	var data= JSON.parse(sessionStorage.getItem("data"));
      if (data==null) {
        alert('login dolo');
        $(location).attr('href', "{% url 'index' %}");
      }
    $(document).ready(function(){
      $('#id_name').val(data["name"]);
    });
    </script>
    <div class="ui grid container" style="margin-bottom:5rem;margin-top:10rem">
      <div class="ui breadcrumb">
  <a href="{% url 'index' %}" class="section">Home</a>
  <div class="divider"> / </div>
  <a href="{% url 'forum:index' %}" class="section">Forum</a>
  <div class="divider"> / </div>
  <div class="active section">{{ post.judul }}</div>
</div>
    <table class="ui celled striped table">
      <thead>
        <tr><th colspan="3">
          <h3>{{post.judul}}</h3>
        </th>
      </tr></thead>
      <tbody>
        <tr>
          <td>{{ post.content | safe }}</a></td>
        </tr>
      </tbody>
    </table>

    <table class="ui celled striped table">
      <thead>
        <tr><th colspan="3">
          <h3>Komentar</h3>
        </th>
      </tr></thead>
      <tbody>
        {% for i in comments %}
        <tr>
          <td>{{ i.content }}</td>
          <td class="right aligned collapsing">{{ i.name }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <table class="ui celled striped table">
<form id="form" method="POST" action="{% url 'forum:add_comment' post.pk %}">
      <thead>
        <tr><th colspan="3">
          <h3>Balas Komentar</h3>
        </th>
      </tr></thead>
<tbody>
        {% csrf_token %}
        {{ comment_form }}
<tr>
        <td colspan="2">
        <button type="submit" class="ui button">Submit</button></td>

</tr>

    </tbody>
</form>
    </table>

  </div>
{% endblock %}

app_login/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <script src="{% static 'login_page.js' %}"></script>
    <!-- Page Contents -->
    <div class="pusher">
        <div class="ui inverted vertical masthead center aligned segment">
            <div class="ui container">
                <div class="ui large secondary inverted pointing menu" style="padding:5px; border:0px;">
                    <a class="toc item" style="padding-right: 10px; padding-left: 10px;">
                        <i class="sidebar icon"></i>
                    </a>
                    <a class="header item" style="padding:3px;" id="header-item">
                        <img class="logo" style="margin-right: 10px;" src="{% static 'images/logo-a.jpg' %}">
                        Home
                    </a>

                    <!--
                    <div class="ui fluid category search" style="margin-left: 10px;">
                        <div class="ui icon input">
                            <input class="prompt" type="text" placeholder="Cari perusahaan atau pekerjaan" style="width: 270px;">
                            <i class="search icon"></i>
                        </div>
                        <div class="results"></div>
                    </div>
                    -->

                    <div class="right item" id="login-buttons-menu">
                        <a class="ui inverted button" id="login-mahasiswa-menu">Mahasiswa?</a>
                        <a class="ui inverted button" id="login-perusahaan-menu" onclick="liAuth()">Perusahaan?</a>
                    </div>
                </div>
            </div>

            <div class="ui text container">
                <h1 class="ui inverted header"><b>#CariYangTerbaik</b></h1>
                <h2>Menghubungkan Orang-orang Terbaik dan Perusahaan Terbaik</h2>
                <div class="ui huge primary button" id="carikerja" style="margin:3px;">Cari Pekerjaan <i class="right arrow icon"></i></div>
                <div class="ui huge primary button" id="cariperu"  onclick="liAuth()" style="margin:3px;">Cari Karyawan <i class="right arrow icon"></i></div>
            </div>
        </div>

        <div class="ui vertical stripe segment">
            <div class="ui text container">
              {% for i in posts %}
                <h2 class="ui header">
                    <img class="ui image" src="{% static 'images/gedung.png' %}">
                    <div class="content">
                        {{i.name}}
                    </div>
                </h2>
                <p>
                {{i.content | safe }}
                </p>
                <a href="{% url 'post' i.pk %}" class="ui large button">Lihat Komentar</a>
                <div class="ui divider"></div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

app_login/templates/postlog.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Page Contents -->
            <div class="ui text container" style="margin-top:10rem;margin-bottom:5rem">
              {% if messages %}
              <strong>Alert</strong>
              <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
              </ul>
              {% endif %}
                <h2 class="ui header">
                    <img class="ui image" src="{% static 'images/gedung.png' %}">
                    <div class="content">
                        {{post.name}}
                    </div>
                </h2>
                <p>
                {{post.content | safe }}
                </p>

                <div class="ui comments" style="margin-top:3rem">
                  <h3 class="ui dividing header">Komentar</h3>
                  {% for i in comments %}
                  <div class="comment">
                    <a class="avatar">
                      {% if i.name == post.name %}
                      <img class="ui image" src="{% static 'images/gedung.png' %}">
                      {% else %}
                      <img src="{% static 'images/matt.jpg' %}">
                      {% endif %}
                    </a>
                    <div class="content">
                      <a class="author">{{i.name}}</a>
                      <div class="metadata">
                        <span class="date">{{i.created_date}}</span>
                      </div>
                      <div class="text">
                        {{i.content}}
                      </div>
                    </div>
                </div>
                {% endfor %}
                <h3 class="ui dividing header" style="margin-top:3rem">Balas Komentar</h3>
                <form class="ui form" method="POST" action="{% url 'add_commentlog' post.pk %}">
                  {% csrf_token %}
                  <div class="field">
                    <label>Nama</label>
                    <input name="name"  type="text">
                  </div>
                  <div class="field">
                    <label>Komentar</label>
                    <textarea name="content"></textarea>
                  </div>
                  <button type="submit" class="ui button">Submit</button>
                  <div class="ui error message"></div>
                </form>
            </div>
</div>

{% endblock %}

app_profile/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Page Contents -->
    <script>
    var data= JSON.parse(sessionStorage.getItem("data"));
    if (data==null) {
      alert('login dolo');
      $(location).attr('href', "{% url 'index' %}");
    }
    $(document).ready(function(){
      $('#nama').html('<h2 class="ui header">'+data["name"]+'</h2>');
      $('#propic').html('<img class="picture" src="' + data["squareLogoUrl"] + '" alt="profpic" />');
      $('#web').html('<a href='+data["websiteUrl"]+'><h3 class="ui header">'+data["websiteUrl"]+'</h3></a>');
      $('#tipe').html('<h3 class="ui header">'+data["companyType"]["name"]+'</h3>');
      $('#spec').html('<h3 class="ui header">'+data["specialties"]["values"]+'</h3>');
    });
    </script>
    <div class="ui two column centered grid" style="margin-top:5rem; margin-bottom:2rem">
    <div class="column center aligned" id="propic">lol</div>
    <div class="four column centered row">
    <div class="column center aligned" id="nama">lol</div>
  </div>
    <div class="four column centered row">
      <div class="right aligned column">
        <a class="huge ui button" href="{% url 'forum:index' %}">Lihat Forum</a>
        
      </div>
      <div class="left aligned column"><button class="huge ui button">
        Cari Mahasiswa
        </button>
      </div>
    </div>
   </div>
   <div class="ui grid container" style="margin-bottom:5rem">
   <div class="seven column row">
     <div class="three wide column"><h3 class="ui header">Tipe Perusahaan</h3></div>
     <div class="one wide column"><h3 class="ui header">:</h3></div>
     <div class="three wide column" id="tipe"><h3 class="ui header">Nonprofit</h3></div>
   </div>
   <div class="seven column row">
     <div class="three wide column"><h3 class="ui header">Website Perusahaan</h3></div>
     <div class="one wide column"><h3 class="ui header">:</h3></div>
     <div class="three wide column" id="web">lol</div>
   </div>
   <div class="seven column row">
     <div class="three wide column"><h3 class="ui header">Spesialitas</h3></div>
     <div class="one wide column"><h3 class="ui header">:</h3></div>
     <div class="three wide column" id="spec">lol</div>
   </div>
 </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!-- Standard Meta -->
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

        <!-- Site Properties -->
        <title>T2KA</title>
        <link rel="icon" href="static/images/logo-a.jpg">

        <!-- Styles -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.1/dist/semantic.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />    

        <!-- JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.1/dist/semantic.min.js"></script>
        <script src="{% static 'js/base.js' %}"></script>
        <!-- Linkedin Login -->
        <script type="text/javascript" src="//platform.linkedin.com/in.js">
            api_key:   78qqeyrwubzt92
            authorize: true
            onLoad: onLinkedInLoad
        </script>
        <script type="text/javascript" src="{% static 'js/linkedin_login.js' %}"></script>
    
    </head>

    <body>
        <!--<div id="cover" ><img src="{% static 'images/rolling.gif' %}" style="display:block; position: absolute; top:0; left: 0; right: 0; bottom: 0; margin: auto;"></div>-->

        <div id="container">
            {% include "sidebar.html" %}

            <header>
                {% include "header.html" %}
            </header>
    
            {% block content %}
            {% endblock %}
    
            <footer>
                {% include "footer.html" %}
            </footer>
        </div>
    </body>
</html>

templates/footer.html
{% load static %}
<div class="ui inverted vertical footer segment">
    <div class="ui center aligned container">
        <img src="{% static 'images/logo-a.jpg' %}" class="ui centered mini image">
        <div class="ui horizontal inverted small divided link list">
            <a class="item" href="#">Site Map</a>
            <a class="item" href="#">Contact Us</a>
            <a class="item" href="#">Terms and Conditions</a>
            <a class="item" href="#">Privacy Policy</a>
        </div>
    </div>
</div>

templates/header.html
<!-- Following Menu -->
{% load static %}
<div class="ui large top fixed inverted menu">
    <div class="ui container">
        <a href="{% url 'index' %}" class="header item" id="navbar-item">
            <img class="logo" style="margin-right: 10px;" src="{% static 'images/logo-a.jpg' %}">
            Home
        </a>
        <div class="right menu" id="login-buttons-navbar">
            <div class="item" id="login-mahasiswa-navbar">
                <a class="ui primary button">Cari Pekerjaan</a>
            </div>
            <div class="item">
                <a class="ui primary button" id="login-perusahaan-navbar" onclick="liAuth()">Cari Karyawan</a>
            </div>
        </div>
    </div>
</div>

templates/sidebar.html
<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
    <a class="active item">Home</a>
    <a class="item">About Us</a>
    <a class="item">Cari Pekerjaan</a>
    <a class="item">Cari Karyawan</a>
</div>